server:
  port: 8090 # puerto Gateway

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          # Aquí va el dominio de tu aplicación en Auth0 (debe terminar con una barra al final '/')
          issuer-uri: https://logintienda.us.auth0.com/
          # Aquí va el Identifier que le pusiste a tu API (el que configuramos en el paso anterior)
          audiences: https://microserv.com.ar